"""create users transactions feedback and metrics tables

Revision ID: fcfe1b3164f7
Revises: 
Create Date: 2026-03-25 01:07:46.890031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcfe1b3164f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('analyst_id', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_feedback_transaction_id'), 'analyst_feedback', ['transaction_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('auroc', sa.Float(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=False),
    sa.Column('recall_score', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('false_positive_rate', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_category', sa.String(length=50), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.Column('model_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('scoring_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_decision'), 'transactions', ['decision'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_category'), 'transactions', ['merchant_category'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('home_latitude', sa.Float(), nullable=False),
    sa.Column('home_longitude', sa.Float(), nullable=False),
    sa.Column('home_country', sa.String(length=2), nullable=False),
    sa.Column('avg_transaction_amount', sa.Float(), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('profile_type', sa.String(length=30), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_decision'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_analyst_feedback_transaction_id'), table_name='analyst_feedback')
    op.drop_table('analyst_feedback')
    # ### end Alembic commands ###
